F    0.116197
C    0.111842
G    0.087781

Kentucky          22
Duke              21
UCLA              11
Gonzaga           11
Michigan          10
North Carolina    10
Kansas            10
Tennessee          9
Arizona            9
Villanova          9

In [23]:
ncaa.groupby('POS')['Drafted'].mean().sort_values(ascending=False)

POS
F    0.116197
C    0.111842
G    0.087781
Name: Drafted, dtype: float64

In [22]:
ncaa[ncaa['Drafted'] == 1]['Team'].value_counts().head(10)

Team
Kentucky          22
Duke              21
UCLA              11
Gonzaga           11
Michigan          10
North Carolina    10
Kansas            10
Tennessee          9
Arizona            9
Villanova          9
Name: count, dtype: int64

9.87 percent drafted

In [ ]:
draft_percentage = ncaa['Drafted'].mean() * 100
draft_percentage

np.float64(9.869419981779533)

In [18]:
qualified = ncaa[ncaa['GP'] >= 20]

qualified.nlargest(10, 'PPG')[['Player', 'Team', 'PPG']]

              Player        Team        PPG
1308      Trae Young    Oklahoma  27.375000
3235       Zach Edey      Purdue  25.205128
1885   Markus Howard   Marquette  25.029412
3044     Buddy Hield    Oklahoma  25.000000
2633  Carsen Edwards      Purdue  24.277778
839       Luka Garza        Iowa  24.096774
677     Stefan Moody    Ole Miss  23.580645
1762  Anthony Barber    NC State  23.515152
2346   Keegan Murray        Iowa  23.485714
125   Markelle Fultz  Washington  23.160000

In [19]:
ncaa.nlargest(10, 'PTS')[['Player', 'Team', 'PTS', 'PPG']]

              Player            Team  PTS        PPG
3235       Zach Edey          Purdue  983  25.205128
3044     Buddy Hield        Oklahoma  925  25.000000
1308      Trae Young        Oklahoma  876  27.375000
2633  Carsen Edwards          Purdue  874  24.277778
3147    R.J. Barrett            Duke  860  22.631579
1885   Markus Howard       Marquette  851  25.029412
2346   Keegan Murray            Iowa  822  23.485714
3030      Drew Timme         Gonzaga  786  21.243243
1844    Myles Powell      Seton Hall  784  23.058824
2956        RJ Davis  North Carolina  784  21.189189

In [16]:
ncaa.groupby('Drafted')[['PPG', 'RPG', 'APG']].mean()

               PPG       RPG       APG
Drafted
0        11.878479  4.573434  2.210155
1        15.026547  5.970683  2.645281

In [15]:
ncaa.groupby('POS')['Drafted'].mean()

POS
C    0.111842
F    0.116197
G    0.087781
Name: Drafted, dtype: float64

In [14]:
ncaa['POS'].value_counts()

POS
G    2005
F    1136
C     152
Name: count, dtype: int64

In [13]:
ncaa.groupby('POS')[['PTS', 'AST', 'TRB']].mean()

            PTS        AST         TRB
POS
C    394.638158  35.414474  235.907895
F    391.194542  47.459507  204.239437
G    401.839401  91.456858  119.769077

In [12]:
ncaa['PPG'] = ncaa['PTS'] / ncaa['GP']
ncaa['RPG'] = ncaa['TRB'] / ncaa['GP']
ncaa['APG'] = ncaa['AST'] / ncaa['GP']

ncaa[['Player', 'PPG', 'RPG', 'APG']].head()

            Player        PPG       RPG       APG
0  James Bouknight  18.733333  5.666667  1.800000
1     Caris LeVert  16.466667  5.333333  4.933333
2      B.J. Taylor  15.875000  2.000000  3.187500
3   Emanuel Miller  16.235294  8.235294  1.411765
4       Dylan Disu  15.000000  9.235294  1.352941

In [11]:
elite_guards = ncaa[(ncaa['POS'] == 'G') & (ncaa['PTS'] >= 400)]
elite_guards[['Player', 'PTS', 'POS']].head()

                    Player  PTS POS
41       Scotty Pippen Jr.  457   G
82             Remy Martin  440   G
88             Josh Okogie  437   G
98   Javon Freeman-Liberty  520   G
102        Nah'Shon Hyland  467   G

In [10]:
high_scorers = ncaa[ncaa['PTS'] > 500]
print(f"High scorers: {len(high_scorers)}")

High scorers: 611

In [9]:
scoring = ncaa[['Player', 'Team', 'PTS', 'GP']]
scoring.head()

            Player         Team  PTS  GP
0  James Bouknight  Connecticut  281  15
1     Caris LeVert     Michigan  247  15
2      B.J. Taylor          UCF  254  16
3   Emanuel Miller    Texas A&M  276  17
4       Dylan Disu   Vanderbilt  255  17

In [8]:
ncaa.isna().sum()

Player       0
Season       0
Team         0
GP           0
GS           0
MP           0
FG           0
FGA          0
2P           0
2PA          0
3P           0
3PA          0
FT           0
FTA          0
ORB          0
DRB          0
TRB          0
AST          0
STL          0
BLK          0
TOV          0
PF           0
PTS          0
FG%          0
2P%          0
3P%        167
FT%          0
TS%          0
eFG%         0
POS          0
Class        0
Drafted      0
dtype: int64

In [7]:
ncaa.columns

Index(['Player', 'Season', 'Team', 'GP', 'GS', 'MP', 'FG', 'FGA', '2P', '2PA',
       '3P', '3PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK',
       'TOV', 'PF', 'PTS', 'FG%', '2P%', '3P%', 'FT%', 'TS%', 'eFG%', 'POS',
       'Class ', 'Drafted'],
      dtype='object')

In [6]:
ncaa.describe()

,GP,GS,MP,FG,FGA,2P,2PA,3P,3PA,FT,...,TOV,PF,PTS,FG%,2P%,3P%,FT%,TS%,eFG%,Drafted
count,3293.000000,3293.000000,3293.000000,3293.000000,3293.000000,3293.000000,3293.000000,3293.000000,3293.000000,3293.000000,...,3293.000000,3293.000000,3293.000000,3293.000000,3293.000000,3126.000000,3293.000000,3293.000000,3293.000000,3293.000000
mean,32.754327,27.775585,947.320377,139.908898,307.375949,99.655937,195.725478,40.252961,111.650471,77.764045,...,56.978743,70.353173,397.834801,0.459016,0.503231,0.338594,0.744838,0.558046,0.523156,0.098694
std,3.680110,9.000728,175.089721,40.279833,84.888148,43.558933,75.218870,27.090933,69.285879,35.682581,...,20.045229,18.366032,113.730216,0.068783,0.070751,0.102225,0.088795,0.048224,0.055262,0.298296
min,15.000000,0.000000,464.000000,72.000000,140.000000,9.000000,29.000000,0.000000,0.000000,11.000000,...,12.000000,18.000000,246.000000,0.305000,0.238000,0.000000,0.352000,0.408000,0.340000,0.000000
25%,31.000000,24.000000,817.000000,108.000000,242.000000,68.000000,141.000000,19.000000,60.000000,52.000000,...,42.000000,58.000000,305.000000,0.410000,0.455000,0.310000,0.689000,0.524000,0.484000,0.000000
50%,33.000000,31.000000,955.000000,133.000000,294.000000,94.000000,186.000000,40.000000,114.000000,71.000000,...,55.000000,70.000000,378.000000,0.445000,0.498000,0.352000,0.753000,0.555000,0.518000,0.000000
75%,35.000000,34.000000,1075.000000,164.000000,361.000000,125.000000,239.000000,58.000000,159.000000,96.000000,...,70.000000,83.000000,466.000000,0.494000,0.549000,0.389000,0.810000,0.589000,0.557000,0.000000
max,41.000000,41.000000,1474.000000,336.000000,703.000000,335.000000,537.000000,147.000000,380.000000,310.000000,...,167.000000,141.000000,983.000000,0.770000,0.770000,1.000000,0.984000,0.739000,0.770000,1.000000

In [3]:
ncaa.shape

(3293, 32)

In [5]:
ncaa.columns

Index(['Player', 'Season', 'Team', 'GP', 'GS', 'MP', 'FG', 'FGA', '2P', '2PA',
       '3P', '3PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK',
       'TOV', 'PF', 'PTS', 'FG%', '2P%', '3P%', 'FT%', 'TS%', 'eFG%', 'POS',
       'Class ', 'Drafted'],
      dtype='object')

In [ ]:
import pandas as pd

ncaa = pd.read_csv("Data/ncaa_data.csv")
ncaa.head()

,Player,Season,Team,GP,GS,MP,FG,FGA,2P,2PA,...,PTS,FG%,2P%,3P%,FT%,TS%,eFG%,POS,Class,Drafted
0,James Bouknight,2020-21,Connecticut,15,14,475,98,219,76,144,...,281,0.447,0.528,0.293,0.778,0.546,0.498,G,SO,1
1,Caris LeVert,2015-16,Michigan,15,14,464,82,162,53,97,...,247,0.506,0.546,0.446,0.794,0.636,0.596,G,SR,1
2,B.J. Taylor,2017-18,UCF,16,14,495,80,201,54,134,...,254,0.398,0.403,0.388,0.673,0.510,0.463,G,JR,0
3,Emanuel Miller,2020-21,Texas A&M,17,13,538,100,175,100,169,...,276,0.571,0.592,0.000,0.817,0.630,0.571,F,SO,0
4,Dylan Disu,2020-21,Vanderbilt,17,17,537,89,181,65,116,...,255,0.492,0.560,0.369,0.736,0.592,0.558,F,SO,0